### ISSUE TITLE
Parameter platformname OR platformid is required

### ISSUE THREAD

**Issue by fabisento** [Beanking77/Robot-Framework-Report-update-to-Testlink#4]
Hi,

i am using Testlink Version : "https://github.com/TestLinkOpenSourceTRMS/testlink-code/tree/testlink_1_9_20_fixed"

wen i do this : python updater.py -p "test" -t "test1" -f "chrome" -b V1 --file test-output.xml

I added a platform in the test link but it doesn't work
i always get this error:

testlink.testlinkerrors.TLResponseError: 200: (reportTCResult) - Parameter platformname OR platformid is required, but has not been provided
reportTCResult({'devKey': 'fgdfgdfgdfgdfgdfgdfg', 'testcaseid': '4', 'testplanid': '2', 'buildname': 'V1', 'status': 'f', 'notes': ''})

Thx

**Comment by fabisento** [comment]
solved:
change this on line 187:

```
def reportTCResult(self):

        for name, pass_id in testcase_id_result_dict["p"]:

            self.robotI.reportTCResult(pass_id, self.TPid, self.build_name, "p", self.PLid, testcase_id_result_dict)

        for name, pass_id in testcase_id_result_dict["f"]:

            self.robotI.reportTCResult(pass_id, self.TPid, self.build_name, "f", self.PLid, testcase_id_result_dict)
```

**Comment by Beanking77** [comment]
Hi @fabisento 

Sorry for the late reply since I'm not using this tool recently.
I'm glad to heard that you solved the issue and welcome to create a PR. :)

Cheers,
